package com.sapientia.wifilistener;

import java.util.ArrayList;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.ActionBarDrawerToggle;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBarActivity;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;
import android.widget.TextView;

import com.sapientia.wifilistener.navigationdrawer.AddNewChannelFragment;
import com.sapientia.wifilistener.navigationdrawer.BaseFragment;
import com.sapientia.wifilistener.navigationdrawer.ChannelFragment;
import com.sapientia.wifilistener.navigationdrawer.DrawerListAdaper;
import com.sapientia.wifilistener.navigationdrawer.MainFragment;
import com.sapientia.wifilistener.navigationdrawer.NavDrawerAddNewChannel;
import com.sapientia.wifilistener.navigationdrawer.NavDrawerChannel;
import com.sapientia.wifilistener.navigationdrawer.NavDrawerExit;
import com.sapientia.wifilistener.navigationdrawer.NavDrawerItem;
import com.sapientia.wifilistener.navigationdrawer.NavDrawerRefresh;
import com.sapientia.wifilistener.navigationdrawer.RefreshListFragment;


public class MainActivity extends ActionBarActivity implements InitApplication {

	private static final int RESULT_SETTINGS = 1;

	private DrawerLayout mDrawerLayout;
	private ListView mDrawerList;
	private ActionBarDrawerToggle mDrawerToggle;
	private DrawerListAdaper adapter;
	private HandleServices handleServices = null;
	
	private BaseFragment fragment = null;
	
	private ArrayList<NavDrawerItem> autoGenerated;
	
	int clientId = 0;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		
		mDrawerLayout = (DrawerLayout) findViewById(R.id.drawer_layout);
		mDrawerList = (ListView) findViewById(R.id.list_slidermenu);

		mDrawerList.setOnItemClickListener(new SlideMenuClickListener());
		
		//initialize navigation lists
		this.initializeNavDrawerLists();
		

		// setting the nav drawer list adapter
		adapter = new DrawerListAdaper(getApplicationContext());
		adapter.setAutogeneratedList(autoGenerated);
		
		//set the adapter
		mDrawerList.setAdapter(adapter);
		
		//generate list
		this.generateNavDrawerList();
		

		mDrawerToggle = new ActionBarDrawerToggle(this, mDrawerLayout,
				R.drawable.drawer, // nav menu toggle icon
				R.string.app_name, // nav drawer open - description for
									// accessibility
				R.string.app_name // nav drawer close - description for
									// accessibility
		) {
			public void onDrawerClosed(View view) {
				getActionBar().setTitle("WifiListener");
				// calling onPrepareOptionsMenu() to show action bar icons
				invalidateOptionsMenu();
			}

			public void onDrawerOpened(View drawerView) {
				getActionBar().setTitle("Channels Online");
				// calling onPrepareOptionsMenu() to hide action bar icons
				invalidateOptionsMenu();
			}
		};
		
		mDrawerLayout.setDrawerListener(mDrawerToggle);
		

	}
	
	private void initializeNavDrawerLists() {
		this.autoGenerated = new ArrayList<NavDrawerItem>();
	}
	
	private void generateNavDrawerList() {
		NavDrawerItem addNewChannel = new NavDrawerAddNewChannel("Add new channel", adapter);
		NavDrawerItem refresh = new NavDrawerRefresh("Refresh List");
		NavDrawerItem exit = new NavDrawerExit("Exit");
		autoGenerated.add(addNewChannel);
		autoGenerated.add(refresh);
		autoGenerated.add(exit);
	}

	@Override
	public void onResume() {
		super.onResume();
		if(handleServices == null) {
			handleServices = new HandleServices(this.getApplicationContext(), this);
		}
		handleServices.startServices();
	}
	
	@Override
	public void onResumeFragments() {
		super.onResumeFragments();
	}

	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		
		getMenuInflater().inflate(R.menu.main, menu);
		return true;
	}

	@Override
	public boolean onOptionsItemSelected(MenuItem item) {
		if (mDrawerToggle.onOptionsItemSelected(item)) {
			return true;
		}
		int id = item.getItemId();
		if (id == R.id.action_settings) {
			Intent i = new Intent(this, SettingsActivity.class);
			startActivityForResult(i, RESULT_SETTINGS);
			return true;
		}
		return super.onOptionsItemSelected(item);
	}
	
	@Override
	public boolean onPrepareOptionsMenu(Menu menu) {
		// if nav drawer is opened, hide the action items
		boolean drawerOpen = mDrawerLayout.isDrawerOpen(mDrawerList);
		menu.findItem(R.id.action_settings).setVisible(!drawerOpen);
		return super.onPrepareOptionsMenu(menu);
	}

	@Override
	public void onPause() {
		super.onStop();
		if(!handleServices.isAuthenticated()) {
			handleServices.distroy();
		}
		else {
			handleServices.unbindServices();
		}
	}

	private void displayView(int position) {
		// update the main content by replacing fragments
		if(position >= 0) {
			NavDrawerItem item = (NavDrawerItem) adapter.getItem(position);
			fragment = item.getFragment();
		}
		else {
			fragment = new MainFragment();
		}

		if (fragment != null) {
			fragment.setServiceHandler(handleServices);
			FragmentManager fragmentManager = this.getSupportFragmentManager();
			fragmentManager.beginTransaction()
					.replace(R.id.frame_container, fragment).commit();

			// update selected item and title, then close the drawer
			mDrawerList.setItemChecked(position, true);
			mDrawerList.setSelection(position);
			setTitle("WifiListener");
			mDrawerLayout.closeDrawer(mDrawerList);
		} 
		else {
			// error in creating fragment
			Log.e("MainActivity", "Error in creating fragment");
		}
	}
	
	private void updateMainFragmentStatus(String status, boolean authBtn) {
		if(fragment instanceof MainFragment) {
			MainFragment mainFragment = (MainFragment)fragment;
			mainFragment.updateStatus(status, authBtn);
		}
	}

	private class SlideMenuClickListener implements
			ListView.OnItemClickListener {
		@Override
		public void onItemClick(AdapterView<?> parent, View view, int position,
				long id) {
			// display view for selected nav drawer item
			displayView(position);
		}
	}

	@Override
	public void showFragment(int pos) {
		//if authentification was successful, then enable actionbar for navigationdrawer
		if(handleServices.isAuthenticated()) {
			enableActionBar();
		}
		else {
			disableActionBar();
		}
		displayView(pos);
	}

	@Override
	public void initNavDrawerModel(ArrayList<NavDrawerItem> fromServer,
			ArrayList<NavDrawerItem> fromUser) {
		adapter.setFromServerList(fromServer);
		adapter.setFromUserList(fromUser);
	}

	@Override
	public void initNavDrawerModelFromServer(ArrayList<NavDrawerItem> fromServer) {
		adapter.setFromServerList(fromServer);
		if(fragment instanceof RefreshListFragment) {
			RefreshListFragment refreshFragment = (RefreshListFragment) fragment;
			refreshFragment.refreshOk();
		}
	}

	@Override
	public void adapterDataChanged() {
		adapter.notifyUpdate();
		if(fragment != null) {
			if(fragment instanceof ChannelFragment) {
				ChannelFragment channelFragment = (ChannelFragment) fragment;
				channelFragment.updateButtonStatus();
			}
		}
	}

	@Override
	public void initAuthFrame() {
		Log.d(Constants.LOG, "initAuthFrame");
		showFragment(-1);
		updateMainFragmentStatus("Server Down!", true);
	}

	@Override
	public void authResult(boolean result) {
		if(result) {
			updateMainFragmentStatus("Authentification success!", false);
			enableActionBar();
		}
		else {
			updateMainFragmentStatus("Authentification failed!", true);
		}
	}
	
	// enabling action bar app icon and behaving it as toggle button
	private void enableActionBar() {
		getActionBar().setDisplayHomeAsUpEnabled(true);
		getActionBar().setHomeButtonEnabled(true);
	}
	
	//  action bar app icon and behaving it as toggle button
	private void disableActionBar() {
		getActionBar().setDisplayHomeAsUpEnabled(false);
		getActionBar().setHomeButtonEnabled(false);
	}


}
