package com.sapientia.wifilistener.navigationdrawer;

import java.util.ArrayList;
import com.sapientia.wifilistener.R;
import com.sapientia.wifilistener.ReceiveService.STATE;

import android.app.Activity;
import android.content.Context;
import android.support.v4.app.Fragment;
import android.text.Layout;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.ImageView;
import android.widget.TextView;

public class DrawerListAdaper extends BaseAdapter {
	
	private ArrayList<NavDrawerItem> fromServer = null;
	private ArrayList<NavDrawerItem> fromUser = null;
	private ArrayList<NavDrawerItem> autoGenerated = null;
	private ArrayList<NavDrawerItem> fullMenu = new ArrayList<NavDrawerItem>();
	private Context context;
	
	public DrawerListAdaper(Context context) {
		this.context = context;
	}
	
	private void generateFullMenu() {
		fullMenu.clear();
		NavDrawerSectionTitle fromServerTitle = new NavDrawerSectionTitle("Channels Online");
		NavDrawerSectionTitle fromUserTitle = new NavDrawerSectionTitle("Localy created");
		NavDrawerSectionTitle autoGenTitle = new NavDrawerSectionTitle("Options");
		fullMenu.add(fromServerTitle);
		if(fromServer != null) {
			fullMenu.addAll(fromServer);
		}
		fullMenu.add(fromUserTitle);
		if(fromUser != null) {
			fullMenu.addAll(fromUser);
		}
		fullMenu.add(autoGenTitle);
		if(autoGenerated != null) {
			fullMenu.addAll(autoGenerated);
		}
		
	}
	
	public void setFromServerList(ArrayList<NavDrawerItem> fromServer) {
		this.fromServer = fromServer;
		generateFullMenu();
		this.notifyDataSetChanged();
	}
	
	public void setFromUserList(ArrayList<NavDrawerItem> fromUser) {
		this.fromUser = fromUser;
		generateFullMenu();
		this.notifyDataSetChanged();
	}
	
	public void setAutogeneratedList(ArrayList<NavDrawerItem> autoGenerated) {
		this.autoGenerated = autoGenerated;
		generateFullMenu();
		this.notifyDataSetChanged();
	}
	
	public void addChannelFromUser(NavDrawerChannel channel) {
		this.fromUser.add(channel);
		generateFullMenu();
		this.notifyDataSetChanged();
	}
	
	public void notifyUpdate() {
		generateFullMenu();
		this.notifyDataSetChanged();
	}

	@Override
	public int getCount() {
		return fullMenu.size();
	}
	
	@Override
	public int getItemViewType(int position) {
		NavDrawerItem item = fullMenu.get(position);
		return item.type();
	}
	
	@Override
	public int getViewTypeCount() {
		return 3;
	}

	@Override
	public Object getItem(int position) {
		if(fullMenu != null) {
			return fullMenu.get(position);
		}
		else {
			return null;
		}
	}

	@Override
	public long getItemId(int position) {
		return position;
	}

	@Override
	//ugly function here, f*ck SOLID principle
	public View getView(int position, View convertView, ViewGroup parent) {
		if(getItemViewType(position) == NavDrawerItem.TYPE_CHANNEL) {
			
			if (convertView == null) {
	            LayoutInflater mInflater = (LayoutInflater)
	                    context.getSystemService(Activity.LAYOUT_INFLATER_SERVICE);
	            convertView = mInflater.inflate(R.layout.list_channel_item, null);
	        }
			
			TextView txtTitle = (TextView) convertView.findViewById(R.id.channelTitle);
			TextView txtSubTitle = (TextView) convertView.findViewById(R.id.subtitle);
			
			NavDrawerChannel item = (NavDrawerChannel) getItem(position);
			txtTitle.setText(item.getTitle());
			txtSubTitle.setText(item.getSubtitle());
			
//			TextView state = (TextView) convertView.findViewById(R.id.playing);
//			
//			if(item.getState() == STATE.PLAYING) {
//				state.setVisibility(View.VISIBLE);
//        	}
//        	else {
//        		state.setVisibility(View.INVISIBLE);
//        	}
		}
		
		if(getItemViewType(position) == NavDrawerItem.TYPE_OPTION) {
			
			if (convertView == null) {
	            LayoutInflater mInflater = (LayoutInflater)
	                    context.getSystemService(Activity.LAYOUT_INFLATER_SERVICE);
	            convertView = mInflater.inflate(R.layout.list_option_item, null);
	        }
			
			TextView txtTitle = (TextView) convertView.findViewById(R.id.optionTitle);
			
			NavDrawerOption item = (NavDrawerOption) getItem(position);
			txtTitle.setText(item.getTitle());
			
			ImageView icon = (ImageView) convertView.findViewById(R.id.optionIcon);
			icon.setImageResource(item.getIconRes());
			
			
		}
		
		if(getItemViewType(position) == NavDrawerItem.TYPE_SECTION_TITLE) {
			
			if (convertView == null) {
	            LayoutInflater mInflater = (LayoutInflater)
	                    context.getSystemService(Activity.LAYOUT_INFLATER_SERVICE);
	            convertView = mInflater.inflate(R.layout.list_sectiontitle_item, null);
	        }
			
			TextView txtTitle = (TextView) convertView.findViewById(R.id.sectionTitle);
			
			NavDrawerSectionTitle item = (NavDrawerSectionTitle) getItem(position);
			txtTitle.setText(item.getTitle());
			
			
		}
        
        return convertView;
	}

}
