package com.sapientia.wifilistener.navigationdrawer;

import java.util.ArrayList;
import com.sapientia.wifilistener.R;

import android.app.Activity;
import android.content.Context;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.ImageView;
import android.widget.TextView;

public class DrawerListAdaper extends BaseAdapter {
	
	private ArrayList<NavDrawerItem> fromServer = null;
	private ArrayList<NavDrawerItem> fromUser = null;
	private ArrayList<NavDrawerItem> autoGenerated = null;
	private Context context;
	
	public DrawerListAdaper(Context context) {
		this.context = context;
	}
	
	public void setFromServerList(ArrayList<NavDrawerItem> fromServer) {
		this.fromServer = fromServer;
	}
	
	public void setFromUserList(ArrayList<NavDrawerItem> fromUser) {
		this.fromUser = fromUser;
	}
	
	public void setAutogeneratedList(ArrayList<NavDrawerItem> autoGenerated) {
		this.autoGenerated = autoGenerated;
	}
	
	public void addChannel(NavDrawerChannel channel) {
		this.fromUser.add(channel);
		this.notifyDataSetChanged();
	}

	@Override
	public int getCount() {
		int count = 0;
		if(fromServer != null) {
			count += fromServer.size();
		}
		
		if(fromUser != null) {
			count += fromUser.size();
		}
		
		if(autoGenerated != null) {
			count += autoGenerated.size();
		}
		return count;
	}

	@Override
	public Object getItem(int position) {
		int fromServerSize = 0;
		int fromUserSize = 0;
		int autoGenSize = 0;
		if(fromServer != null) {
			fromServerSize = fromServer.size();
		}
		if(fromUser != null) {
			fromUserSize = fromUser.size();
		}
		if(autoGenerated != null) {
			autoGenSize = autoGenerated.size();
		}
		
		if(position < fromServerSize) {
			return fromServer.get(position);
		}
		else {
			if(position - fromServerSize < fromUserSize) {
				return fromUser.get(position - fromServerSize);
			}
			else {
				return autoGenerated.get(position - fromServerSize - fromUserSize);
			}
		}
	}

	@Override
	public long getItemId(int position) {
		return position;
	}

	@Override
	public View getView(int position, View convertView, ViewGroup parent) {
		if (convertView == null) {
            LayoutInflater mInflater = (LayoutInflater)
                    context.getSystemService(Activity.LAYOUT_INFLATER_SERVICE);
            convertView = mInflater.inflate(R.layout.list_item, null);
        }
         
        TextView txtTitle = (TextView) convertView.findViewById(R.id.title);
        
        NavDrawerItem item = (NavDrawerItem) getItem(position);
        txtTitle.setText(item.getTitle());
        
        // displaying count
        // check whether it set visible or not
//        if(navDrawerItems.get(position).getCounterVisibility()){
//        	txtCount.setText(navDrawerItems.get(position).getCount());
//        }else{
//        	// hide the counter view
//        	txtCount.setVisibility(View.GONE);
//        }
        
        return convertView;
	}

}
